run:
  deadline: 10m

linters:
  enable:
    - unused
    - deadcode
    - gosimple
    - gofmt
    - govet
    - staticcheck
    - unparam
    - unconvert
    - errcheck
    - ineffassign
    - misspell
    - bodyclose
  disable-all: true

issues:
  exclude-rules:
  - linters:
    - unparam
    text: \(\*leaseStep\)\.Provides\$1 - result 1 \(error\) is always nil
  - linters:
    - staticcheck
    # Code has a "Deprecated:" comment
    text: "SA1019:"
